### ISSUE TITLE
Unable to cover by golden test TickerText widget.

### ISSUE THREAD

**Issue by Alexi-Zemcov** [arafatamim/ticker_text#3]
Whan I covered TickerText by goldens it crash with a error below:
```
Pending timers:
Timer (duration: 0:00:10.000000, periodic: false), created:
#0      new FakeTimer._ (package:fake_async/fake_async.dart:308:62)
#1      FakeAsync._createTimer (package:fake_async/fake_async.dart:252:27)
#2      FakeAsync.run.<anonymous closure> (package:fake_async/fake_async.dart:185:19)
#6      _TickerTextState._scroll (package:ticker_text/ticker_text.dart:134:20)
#7      _TickerTextState.initState.<anonymous closure> (package:ticker_text/ticker_text.dart:99:59)
#8      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1146:15)
#9      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1091:9)
#10     AutomatedTestWidgetsFlutterBinding.pump.<anonymous closure> (package:flutter_test/src/binding.dart:1050:9)
#13     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:71:41)
#14     AutomatedTestWidgetsFlutterBinding.pump (package:flutter_test/src/binding.dart:1037:27)
#15     WidgetTester.pumpWidget.<anonymous closure> (package:flutter_test/src/widget_tester.dart:548:22)
#18     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:71:41)
#19     WidgetTester.pumpWidget (package:flutter_test/src/widget_tester.dart:545:27)
#20     _pumpAppWidget (package:golden_toolkit/src/testing_tools.dart:128:16)
<asynchronous suspension>
<asynchronous suspension>
(elided 8 frames from dart:async and package:stack_trace)

══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following assertion was thrown running a test:
A Timer is still pending even after the widget tree was disposed.
'package:flutter_test/src/binding.dart':
Failed assertion: line 1291 pos 12: '!timersPending'

When the exception was thrown, this was the stack:
#2      AutomatedTestWidgetsFlutterBinding._verifyInvariants (package:flutter_test/src/binding.dart:1291:12)
#3      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:848:7)
<asynchronous suspension>
(elided 2 frames from class _AssertionError)

The test description was:
  TickerText
════════════════════════════════════════════════════════════════════════════════════════════════════

Test failed. See exception logs above.
The test description was: TickerText
```

Test itself looks like this:
```dart
import 'package:flutter/material.dart';
import 'package:golden_toolkit/golden_toolkit.dart';
import 'package:ticker_text/ticker_text.dart';

void main() {
  testGoldens('TickerText', (tester) async {
    await tester.pumpWidgetBuilder(
      const TickerText(child: Text('This is very long long long long long text.....')),
      surfaceSize: const Size(500, 500),
      wrapper: materialAppWrapper(),
    );

    await screenMatchesGolden(tester, 'ticker_text');
  });
}
```

**Comment by arafatamim** [comment]
Hi, could you try the following code and see if it works?
```dart
  testGoldens("TickerTest", (tester) async {
    await tester.runAsync(() async {
      await tester.pumpWidgetBuilder(
        const TickerText(
            child: Text('This is very long long long long long text.....')),
        surfaceSize: const Size(500, 500),
        wrapper: materialAppWrapper(),
      );
      await tester.pumpAndSettle();
    });

    await screenMatchesGolden(tester, 'ticker_text');
  });
```

**Comment by Alexi-Zemcov** [comment]
Thanks alot! Your test is works. You helped me a lot 👍
